baseURL = "https://alecohanesian.com/"
locale = "en-us"
title = "Alec Ohanesian"
theme = "alec"

[params]
  description = "Production Manager & Aerospace Engineer"
  author = "Alec Ohanesian"

[taxonomies]
  genre = "genres"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
